### ISSUE TITLE
Cannot use this Vite plugin with @typescript-eslint/utils

### ISSUE THREAD

**Issue by azat-io** [ota-meshi/vite-plugin-eslint4b#8]
Hi!

I tried to create Monaco editor with ESLint preview on my documentation website. This is the documentation for the ESLint plugin.

But my plugin uses the helpers and types from `@typescript-eslint/utils`. When I try to import rules from my ESLint plugin I get the following error:

```
  vitepress v1.0.0-alpha.75

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
✘ [ERROR] Could not read from file: /Users/azat/Developer/eslint-plugin-perfectionist/virtual:eslint4b_eslint

    node_modules/.pnpm/@typescript-eslint+utils@5.59.5_eslint@8.40.0_typescript@5.0.4/node_modules/@typescript-eslint/utils/dist/ts-eslint/CLIEngine.js:6:25:
      6 │ const eslint_1 = require("eslint");
        ╵                          ~~~~~~~~

✘ [ERROR] Could not read from file: /Users/azat/Developer/eslint-plugin-perfectionist/virtual:eslint4b_eslint/package.json

    node_modules/.pnpm/@typescript-eslint+utils@5.59.5_eslint@8.40.0_typescript@5.0.4/node_modules/@typescript-eslint/utils/dist/eslint-utils/rule-tester/RuleTester.js:54:31:
      54 │ const package_json_1 = require("eslint/package.json");
         ╵                                ~~~~~~~~~~~~~~~~~~~~~

11:13:47 PM [vitepress] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/.pnpm/@typescript-eslint+utils@5.59.5_eslint@8.40.0_typescript@5.0.4/node_modules/@typescript-eslint/utils/dist/eslint-utils/rule-tester/RuleTester.js:54:31: ERROR: Could not read from file: /Users/azat/Developer/eslint-plugin-perfectionist/virtual:eslint4b_eslint/package.json
node_modules/.pnpm/@typescript-eslint+utils@5.59.5_eslint@8.40.0_typescript@5.0.4/node_modules/@typescript-eslint/utils/dist/ts-eslint/CLIEngine.js:6:25: ERROR: Could not read from file: /Users/azat/Developer/eslint-plugin-perfectionist/virtual:eslint4b_eslint
    at failureErrorWithLog (/Users/azat/Developer/eslint-plugin-perfectionist/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/azat/Developer/eslint-plugin-perfectionist/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1048:25
    at /Users/azat/Developer/eslint-plugin-perfectionist/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Does that mean I can't use your Vite plugin because my ESLint plugin imports ESLint?

**Comment by ota-meshi** [comment]
I don't know what is causing the error. Could you share a repository where we can reproduce the issue?

**Comment by azat-io** [comment]
Sorry for the long reply. This example does not work, but you can see the error here:

https://github.com/azat-io/eslint-plugin-perfectionist/pull/1

**Comment by ota-meshi** [comment]
Thanks for sharing the repository. I will try to fix it.
